packages:
  - "."

minimumReleaseAge: 10080
minimumReleaseAgeStrict: true
minimumReleaseAgeExclude:
  - axi-sdk-js
  - lavish-axi
onlyBuiltDependencies:
  - esbuild
allowBuilds:
  esbuild: true
overrides:
  body-parser: 2.3.0
  qs: 6.15.2
